FROM python:3.12 as build
RUN pip install pyinstaller==6.9.0
WORKDIR /app
COPY src/check.py .
RUN pyinstaller --onefile check.py

FROM ubuntu:noble as run
RUN apt-get update && apt-get install -y locales-all
WORKDIR /app
COPY --from=build /app/dist/check .
RUN chmod +x check
ENTRYPOINT [ "./check" ]